### ISSUE TITLE
Create a test report in html format

### ISSUE THREAD

**Issue by natumkur** [tnicola/cypress-parallel#25]
Is it possible for us to generate report in html format

**Comment by prasanmgc** [comment]
I assume, this plugin is mainly for parallel execution of tests using cypress. Why don't you try various reporting plugins in the market? i.e. Allure Reporting, Cucumber HTML Reports, Multiple Cucumber HTML Reports, Mocha Awesome Reports, etc.

**Comment by tnicola** [comment]
Exactly, the aim of the plugin is to run cypress tests in parallel. It has a custom reporter to gather all the results from the running threads. In order to have a html reporter you should specify an external one. If I have time I will try to use a multi-reporter so to have the results formatted in html.
