### ISSUE TITLE
"reporter" parameter is ignored

### ISSUE THREAD

**Issue by oskar-szulc** [tnicola/cypress-parallel#72]
Providing the `--reporter path` parameter doesn't change the hardcoded `--reporter cypress-multi-reporters` value when the command is run.

Being able to provide custom `reporter` path is useful in monorepos, where `node_modules` is not in the same path as the project.

Current behaviour:

When running `cypress-parallel -s test:cypress:headless -t 1 -d tests/e2e/specs/ -r '../../node_modules/cypress-multi-reporters'`

The generated command is: 

`cypress run --config-file tests/e2e/config/local.json --browser chrome '' --spec (...) --reporter cypress-multi-reporters --reporter-options configFile=(...)multi-reporter-config.json`

And my expectation would be to see the provided `reporter` in the generated command:

`cypress run --config-file tests/e2e/config/local.json --browser chrome '' --spec (...) --reporter '../../node_modules/cypress-multi-reporters' --reporter-options configFile=(...)multi-reporter-config.json`

**Comment by oskar-szulc** [comment]
As this seems to be an easy fix I'll be happy to submit a PR.

**Comment by tnicola** [comment]
Hi @oskar-szulc, I understand your point. The problem here is that cypress-parallel needs `cypress-multi-reporters` in order to wrap the results from the parallel threads. If we make the reporter option override it, the library will break in case you will use a different reporter than cypress-multi-reporters.

Cypress has an open issue about this: https://github.com/cypress-io/cypress/issues/6406 if they'll solve this you should be able to get your example working fine.

So a solution here could be adding a new argument containing cypress-multi-reporters path (a bit too customised but it should work). Another solution could be to move cypress-multi-reporters from peerDependencies to dependencies in the library so that it will always be found in the local node_module folder with no need to specify the path.

**Comment by joshuajtward** [comment]
@tnicola @oskar-szulc I've raised a reasonably simple but clunky PR (#81) which should address this issue until (or if...) Cypress fix it on their end. We've been using this in a local patch for some months now and it works smoothly.

**Comment by khuctrang** [comment]
@tnicola Looks like using "--reporterModulePath" parameter should help. I found this in their [npm docs](https://www.npmjs.com/package/cypress-parallel?activeTab=readme).


![image](https://user-images.githubusercontent.com/10876529/155494739-4ffe5a3c-c0f4-4cc0-8689-9e65d2621d88.png)
